version: '3.1'

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
    ports:
      - '5432:5432'
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8890:8080